import { Company, JobSourceConfig } from '../types';
import { JobSourceAdapter, RawJobPayload, RawWalkInPayload } from './JobSourceAdapter';

export const TRACKED_COMPANIES: Company[] = [
  { id: 'tcs', name: 'Tata Consultancy Services (TCS)', officialDomain: 'tcs.com', careersUrl: 'https://www.tcs.com/careers', logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=60', industry: 'IT Services & Consulting', verified: true, activeOpeningsCount: 14 },
  { id: 'infosys', name: 'Infosys', officialDomain: 'infosys.com', careersUrl: 'https://career.infosys.com', logo: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=100&auto=format&fit=crop&q=60', industry: 'IT Services & Consulting', verified: true, activeOpeningsCount: 11 },
  { id: 'accenture', name: 'Accenture', officialDomain: 'accenture.com', careersUrl: 'https://www.accenture.com/in-en/careers', logo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=100&auto=format&fit=crop&q=60', industry: 'Professional Services & IT', verified: true, activeOpeningsCount: 16 },
  { id: 'capgemini', name: 'Capgemini', officialDomain: 'capgemini.com', careersUrl: 'https://www.capgemini.com/careers', logo: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=100&auto=format&fit=crop&q=60', industry: 'IT & Digital Services', verified: true, activeOpeningsCount: 9 },
  { id: 'cognizant', name: 'Cognizant', officialDomain: 'cognizant.com', careersUrl: 'https://careers.cognizant.com', logo: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=100&auto=format&fit=crop&q=60', industry: 'IT Services', verified: true, activeOpeningsCount: 12 },
  { id: 'wipro', name: 'Wipro', officialDomain: 'wipro.com', careersUrl: 'https://careers.wipro.com', logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=60', industry: 'IT Services', verified: true, activeOpeningsCount: 8 },
  { id: 'hcltech', name: 'HCLTech', officialDomain: 'hcltech.com', careersUrl: 'https://www.hcltech.com/careers', logo: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=100&auto=format&fit=crop&q=60', industry: 'Technology Services', verified: true, activeOpeningsCount: 7 },
  { id: 'techmahindra', name: 'Tech Mahindra', officialDomain: 'techmahindra.com', careersUrl: 'https://careers.techmahindra.com', logo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=100&auto=format&fit=crop&q=60', industry: 'IT & Telecom Services', verified: true, activeOpeningsCount: 6 },
  { id: 'ltimindtree', name: 'LTIMindtree', officialDomain: 'ltimindtree.com', careersUrl: 'https://www.ltimindtree.com/careers', logo: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=100&auto=format&fit=crop&q=60', industry: 'Digital Solutions', verified: true, activeOpeningsCount: 5 },
  { id: 'persistent', name: 'Persistent Systems', officialDomain: 'persistent.com', careersUrl: 'https://www.persistent.com/careers', logo: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=100&auto=format&fit=crop&q=60', industry: 'Software Product Engineering', verified: true, activeOpeningsCount: 9 },
  { id: 'mphasis', name: 'Mphasis', officialDomain: 'mphasis.com', careersUrl: 'https://careers.mphasis.com', logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=60', industry: 'Applied Tech Services', verified: true, activeOpeningsCount: 4 },
  { id: 'deloitte', name: 'Deloitte', officialDomain: 'deloitte.com', careersUrl: 'https://www2.deloitte.com/in/en/careers.html', logo: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=100&auto=format&fit=crop&q=60', industry: 'Management & Tech Consulting', verified: true, activeOpeningsCount: 10 },
  { id: 'ibm', name: 'IBM', officialDomain: 'ibm.com', careersUrl: 'https://www.ibm.com/careers', logo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=100&auto=format&fit=crop&q=60', industry: 'Cloud & AI Solutions', verified: true, activeOpeningsCount: 13 },
  { id: 'oracle', name: 'Oracle', officialDomain: 'oracle.com', careersUrl: 'https://www.oracle.com/careers', logo: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=100&auto=format&fit=crop&q=60', industry: 'Cloud Infrastructure & Database', verified: true, activeOpeningsCount: 8 },
  { id: 'microsoft', name: 'Microsoft', officialDomain: 'microsoft.com', careersUrl: 'https://careers.microsoft.com', logo: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=100&auto=format&fit=crop&q=60', industry: 'Software & Cloud', verified: true, activeOpeningsCount: 15 },
  { id: 'amazon', name: 'Amazon', officialDomain: 'amazon.jobs', careersUrl: 'https://www.amazon.jobs/en', logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=60', industry: 'E-Commerce & Cloud (AWS)', verified: true, activeOpeningsCount: 17 },
  { id: 'ey', name: 'EY (Ernst & Young)', officialDomain: 'ey.com', careersUrl: 'https://www.ey.com/en_in/careers', logo: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?w=100&auto=format&fit=crop&q=60', industry: 'Assurance & Tech Consulting', verified: true, activeOpeningsCount: 7 },
  { id: 'kpmg', name: 'KPMG', officialDomain: 'kpmg.com', careersUrl: 'https://kpmg.com/in/en/home/careers.html', logo: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=100&auto=format&fit=crop&q=60', industry: 'Advisory & Tech Services', verified: true, activeOpeningsCount: 5 },
  { id: 'pwc', name: 'PwC India', officialDomain: 'pwc.in', careersUrl: 'https://www.pwc.in/careers.html', logo: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=100&auto=format&fit=crop&q=60', industry: 'Technology Consulting', verified: true, activeOpeningsCount: 6 },
  { id: 'genpact', name: 'Genpact', officialDomain: 'genpact.com', careersUrl: 'https://www.genpact.com/careers', logo: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=100&auto=format&fit=crop&q=60', industry: 'Digital Transformation', verified: true, activeOpeningsCount: 8 }
];

export const INITIAL_SOURCE_CONFIGS: JobSourceConfig[] = [
  { id: 'src-naukri', name: 'Naukri (Permitted RSS/API Feed)', sourceUrl: 'https://www.naukri.com/fresher-java-jobs', sourceType: 'NAUKRI', pollingIntervalMinutes: 3, active: true, status: 'HEALTHY', successCount: 142, errorCount: 0, totalJobsDetected: 84 },
  { id: 'src-linkedin', name: 'LinkedIn Jobs (Public Feed)', sourceUrl: 'https://www.linkedin.com/jobs/search?keywords=java%20fresher', sourceType: 'LINKEDIN', pollingIntervalMinutes: 5, active: true, status: 'HEALTHY', successCount: 98, errorCount: 1, totalJobsDetected: 62 },
  { id: 'src-tcs', name: 'TCS iBegin & Smart Hiring Portal', sourceUrl: 'https://ibegin.tcs.com/iBegin/jobs', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 10, active: true, status: 'HEALTHY', successCount: 45, errorCount: 0, totalJobsDetected: 28 },
  { id: 'src-infosys', name: 'Infosys Careers & Springboard API', sourceUrl: 'https://career.infosys.com/jobs', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 10, active: true, status: 'HEALTHY', successCount: 39, errorCount: 0, totalJobsDetected: 19 },
  { id: 'src-accenture', name: 'Accenture Careers ATS Feed', sourceUrl: 'https://www.accenture.com/in-en/careers/explore-careers', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 10, active: true, status: 'HEALTHY', successCount: 51, errorCount: 0, totalJobsDetected: 33 },
  { id: 'src-cognizant', name: 'Cognizant GenC Career Gateway', sourceUrl: 'https://careers.cognizant.com/in/en', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 15, active: true, status: 'HEALTHY', successCount: 30, errorCount: 0, totalJobsDetected: 17 },
  { id: 'src-persistent', name: 'Persistent Systems Talent Portal', sourceUrl: 'https://www.persistent.com/careers/freshers', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 15, active: true, status: 'HEALTHY', successCount: 22, errorCount: 0, totalJobsDetected: 14 },
  { id: 'src-deloitte', name: 'Deloitte India Campus & USI Portal', sourceUrl: 'https://usirecruiting.deloitte.com', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 15, active: true, status: 'HEALTHY', successCount: 19, errorCount: 0, totalJobsDetected: 11 },
  { id: 'src-amazon', name: 'Amazon University & SDE Talent Portal', sourceUrl: 'https://www.amazon.jobs/en/job_categories/software-development', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 15, active: true, status: 'HEALTHY', successCount: 27, errorCount: 0, totalJobsDetected: 21 },
  { id: 'src-capgemini', name: 'Capgemini Exceller Hiring Portal', sourceUrl: 'https://www.capgemini.com/in-en/careers', sourceType: 'COMPANY_PORTAL', pollingIntervalMinutes: 15, active: true, status: 'HEALTHY', successCount: 33, errorCount: 0, totalJobsDetected: 15 }
];
